import '../models/product.dart';

final List<String> coffeeCategories = [
  'All',
  'Cappuccino',
  'Latte',
  'Espresso',
  'Mocha',
  'Americano',
  'Flat White',
];

final List<Product> mockProducts = [
  Product(
    id: '1',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk and foam.',
    imageUrl: 'assets/img1.png',
    price: 160,
    rating: 4.8,
    category: 'Cappuccino',
    sizes: ['S', 'M', 'L'],
  ),
  Product(
    id: '2',
    name: 'Latte',
    description: 'Rich espresso with steamed milk.',
    imageUrl: 'assets/img2.png',
    price: 180,
    rating: 4.7,
    category: 'Latte',
    sizes: ['S', 'M', 'L'],
  ),
  Product(
    id: '3',
    name: 'Espresso',
    description: 'Strong and bold espresso shot.',
    imageUrl: 'assets/img3.png',
    price: 120,
    rating: 4.6,
    category: 'Espresso',
    sizes: ['S', 'M'],
  ),
  Product(
    id: '4',
    name: 'Mocha',
    description: 'Espresso with chocolate and steamed milk.',
    imageUrl: 'assets/img4.png',
    price: 200,
    rating: 4.9,
    category: 'Mocha',
    sizes: ['S', 'M', 'L'],
  ),
  Product(
    id: '5',
    name: 'Americano',
    description: 'Espresso with added hot water.',
    imageUrl: 'assets/img5.png',
    price: 140,
    rating: 4.5,
    category: 'Americano',
    sizes: ['S', 'M', 'L'],
  ),
  Product(
    id: '6',
    name: 'Flat White',
    description: 'Espresso with microfoam milk.',
    imageUrl: 'assets/img6.png',
    price: 170,
    rating: 4.7,
    category: 'Flat White',
    sizes: ['S', 'M', 'L'],
  ),
];
